language: cpp

services:
  - docker

matrix:
  include:
    - env: PLATFORM=pc
    - env: PLATFORM=wiiu
    - env: PLATFORM=switch

script:
  - docker run -e PLATFORM="$PLATFORM"
               -v $(pwd):/code ubuntu:18.04
               /bin/bash -c "cd /code && ./dependency_helper.sh && ./build.sh"
