name: Build console apps

on:
  push:
    branches:
      - main
      - sdl2-only
  pull_request:
    branches:
      - main

jobs:
  all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: wiiu
            ext: wuhb
          - platform: switch
            ext: nro
          - platform: wii
            ext: dol
          - platform: 3ds
            ext: 3dsx
    container:
      image: ghcr.io/fortheusers/sealeo:sha-1474053
    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - name: Build ${{ matrix.platform }}
      run: make ${{ matrix.platform }}
    - uses: actions/upload-artifact@v3
      with:
        name: vgedit.${{ matrix.ext }}
        path: /__w/vgedit/vgedit/vgedit.${{ matrix.ext }}